### ISSUE TITLE
Import Savers from perftools/xhgui-collector

### ISSUE THREAD

**Issue by glensc** [perftools/xhgui#309]
https://github.com/perftools/php-profiler/pull/29 is merged, and therefore we no longer need `perftools/xhgui-collector` split and we should archive https://github.com/perftools/xhgui-collector project.

# tasks

- [x] import xhgui-collector history: https://github.com/perftools/xhgui/pull/310
- [ ] archive https://github.com/perftools/xhgui-collector @markstory 
- [x] remove all irrelevant parts covering profiling (keep only savers): https://github.com/perftools/xhgui/pull/315
  - [x] drop Xhgui_Saver_Upload, Xhgui_Saver_File: these became pointless. 
  - [x] remove `external/header.php` wrapper here, as that's become unsupported.
- [x] update documentation

refs:
- https://github.com/perftools/xhgui/pull/224
- https://github.com/perftools/xhgui/pull/236

**Comment by glensc** [comment]
cc @perftools/maintainers

**Comment by markstory** [comment]
Sounds like a good plan to me. We'll need to update the README and installation instructions when the header.php file is removed.

**Comment by lauripiisang** [comment]
Cool, makes sense to me! Nice to see the projects coming together 👍

**Comment by glensc** [comment]
@markstory the header.php is not mentioned in the readme at all. I believe it was removed when the xhgui-collector package was split. so there's no documentation to update.

**Comment by glensc** [comment]
@markstory could you please complete task assigned to you?

**Comment by markstory** [comment]
@glensc The xhgui-collector repository has been archived now.
